# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.

theme = "blowfish"
baseURL = "https://candle8.app/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

# OLS @ 03.07.2025 - To add in beta version
googleAnalytics = "G-XXXXXXXXXX"

[pagination]
  pagerSize = 27

[params.author]
  name = "Olivier Essner"
  image = "img/avatar.jpg"
  headline = "Solution Architect / Senior Business Analyst"
  bio = "Solution Architect / Senior Business Analyst"
  links = [
    { email = "mailto:contact@candle8.app" },
    { linkedin = "https://www.linkedin.com/in/olivier-essner-a7b87547" },
    { github = "https://github.com/Olivier-Essner-81" },
  ]


[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 1
  includeNewer = true
  toLower = true

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 10

    [[related.indices]]
        name = "date"
        weight = 0

    [[related.indices]]
      applyFilter = true
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

