languageCode = "en"
languageName = "English"
weight = 1
title = "Candle 8 App"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2025-05-25"
  logo = "img/logo_inverted@0.25x.png"
  secondaryLogo = "img/logo@0.25x.png"
  description = "Candle 8 | App"
  # copyright = "Copyright Candle-8"